version: '3.9'

services:
  app:
    build:
      context: ./bowling-scorecard
    command: npm run dev -- --hostname 0.0.0.0 --port 3000
    ports:
      - '3000:3000'
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    volumes:
      - ./bowling-scorecard:/app
    env_file:
      - ./bowling-scorecard/.env
